# Generated by Django 5.2.4 on 2025-09-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='phone_number',
        ),
    ]
